---
title: "Get alien species data from gbif"
author: "Sander"
date: "5 maart 2018"
output: html_document
---

```{r libraries}
library(tidyverse)
library(rgbif)
library(sf)
library(sp)
library(googleVis)
library(rgdal)
library(leaflet)
require(spatialEco)
```
```{r Prep}
crs_wgs <- CRS("+init=epsg:4326")
crs_BEL72 <- CRS("+proj=lcc +lat_1=49.83333333333334 +lat_2=51.16666666666666 +lat_0=90 +lon_0=4.356939722222222 +x_0=150000.01256 +y_0=5400088.4378 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs")
```

```{r Download WnmBE plants data}
WnmBe_Plants <- occ_download_get(key = "0006843-171025204727650", overwrite = TRUE) %>% 
    occ_download_import(WnmBe_Plants_download, na.strings = c("", NA))
```

```{r read UTM5x5 grid file}
UTM5 <- readOGR("D://Projects/PRJ_Faunabeheer/Algemeen/utmmap/UTM5.shp")
UTM5_WGS <- spTransform(UTM5, crs_wgs)
plot(UTM5)
```

```{r Convert data into spatial file}
WnmBe_Plants$LatLong <- paste(WnmBe_Plants$decimallatitude, ":", WnmBe_Plants$decimallongitude, sep="")
coord <- WnmBe_Plants %>%
    select(decimallongitude, decimallatitude)
WnmBe_Plants_Spatial <-  SpatialPointsDataFrame(coord,
                                           data = WnmBe_Plants,
                                           proj4string = crs_wgs)

plot(WnmBe_Plants_Spatial)

```
```{r Spatial join met UTM5}
WnmBe_Plants_UTM5 <- over(WnmBe_Plants_Spatial, UTM5_WGS )

WnmBe_Plants_UTM5_Species <- bind_cols(WnmBe_Plants,
                                       WnmBe_Plants_UTM5)

```

```{r bereken goed onderzochte Hokken}
WnmBe_Plants_UTM5_Species2 <- WnmBe_Plants_UTM5_Species[,c("scientificname", "TAG", "year")]

WnmBe_Plants_UTM5_Species2 %>% group_by(TAG, year) %>% 
  summarise(n_distinct(scientificname), n()) -> temp

totaal_aant_soorten <- n_distinct(WnmBe_Plants_UTM5_Species2$scientificname)

temp$percentagegevonden <- temp$`n_distinct(scientificname)`/totaal_aant_soorten
temp$dubbelratio <- temp$`n()`/temp$`n_distinct(scientificname)`
temp$gewogenpercentagegevonden <- (temp$`n_distinct(scientificname)`/totaal_aant_soorten)*temp$dubbelratio
summary(temp$percentagegevonden)
ggplot(data = temp, aes(x=percentagegevonden)) + geom_histogram()
summary(temp$gewogenpercentagegevonden)
ggplot(data = temp, aes(x=gewogenpercentagegevonden)) + geom_histogram()
temp$Onderzocht1 <- ifelse(temp$percentagegevonden > 0.0094301, 1, 0)
temp$Onderzocht2 <- ifelse(temp$gewogenpercentagegevonden > 0.0163227, 1, 0)
onderzochtehokken1 <- subset(temp, Onderzocht1 == 1)
onderzochtehokken2 <- subset(temp, Onderzocht2 == 1)
```
```{r add zeroes}
temp2 <- merge(WnmBe_Plants_UTM5_Species2, temp, all.x = T)
specieslist <- unique(temp2$scientificname)

for(s in specieslist){
  
}
```

