---
title: "Bedreiging-door-nieuwe-uitheemse-diersoorten"
author: "Stijn Van Hoey"
date: "September 16, 2016"
output:
  html_document: default
  pdf_document: default
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# run to html with command:
# rmarkdown::render("bedreiging-door-nieuwe-uitheemse-diersoorten.Rmd", output_file = "../reports/html/bedreiging-door-nieuwe-uitheemse-diersoorten.html") 
library(ggplot2)
library(dplyr)
library(INBOtheme)

df_pathway <- read.csv("../data/processed/bedreiging-door-nieuwe-uitheemse-diersoorten-1.csv")
df_count <- read.csv("../data/processed/bedreiging-door-nieuwe-uitheemse-diersoorten-2.csv")

# function to automatically create multiliners for x-axis,
# splitting on the first space after the center
label.splitter <- function(label, maxlength){
    label <- as.character(label)
    if (nchar(label) > maxlength) {
        # find space closest to center of string
        split.space <- nchar(label) %/% 2
        regex.statement <- paste("(^.{", split.space, "})(\\S*)([ ])", sep = "")
        label <- gsub(regex.statement, "\\1\\2\n", label)
    }
    return(label)
}
```

## Pathway overview


```{r, out.extra = 'angle=-90', echo = FALSE, fig.width=12, fig.height=13, message = FALSE, warning = FALSE}
# ISSUE: figure need to be turned 90 degrees... ok in pdf, not in html

df_pathway <- mutate_at(df_pathway, .cols = c("category"), .funs = toupper)

# subcategory add line splits
max.length.allowed <- 30
df_pathway$subcategory <- as.factor(sapply(df_pathway$subcategory,
                                        FUN = label.splitter,
                                        max.length.allowed))
# category add line splits
max.length.allowed <- 20
df_pathway$category <- as.factor(sapply(df_pathway$category,
                                     FUN = label.splitter,
                                     max.length.allowed))

# Create the graph
ggplot(df_pathway, aes(x = reorder(subcategory, -n),
                    y = n, fill = kingdom)) +
    geom_bar(stat = "identity", width = .65) +
    ylab("Number of species") +
    facet_grid(. ~ category, scales = "free_x",
               space = "free_x") +
    theme_inbo2015(base_size = 11) +
    theme(
        axis.text.x = element_text(angle = 90, hjust = 1,
                                   vjust = 0.2, size = 10),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 12, angle = 90,
                                   hjust = 0.5),
        axis.title.y = element_text(size = 14),
        strip.text.x = element_text(angle = 90, size = 12),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.text = element_text(angle = 90, size = 14),
        legend.title = element_blank(),
        legend.text.align = -.6
    )
```


## Cumulative number of species in time

```{r, echo=FALSE, fig.width=9, fig.height=14, warning = FALSE, message = FALSE}

ggplot(data = df_count, aes(x = period_sections, 
                            y = cumcount)) +
                geom_bar(stat = "identity") +
                theme_inbo2015(base_size = 14) +
                facet_grid(habitat_name ~ .) +
                scale_x_discrete(labels = seq(1800, 2030, 15)) +
                xlab("") +
                ylab("Number of alien species") +
                theme(strip.text.y = element_text(size = 16)) +
                scale_x_continuous(breaks = seq(1800, 2010, 50))
```





