---
title: "RST_Losse_Waarnemingen"
author: "Sander Devisscher", "Tim Adriaens"
date: "25 juli 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  fig.width = 147 / 25.4,
  fig.height = 103 / 25.4,
  dpi = 300
)
```

```{r libraries}
library(INBOtheme)
library(lubridate)
library(tidyverse)

check <- function(x){tryCatch(if(class(x) == 'logical') 1 else 1, error=function(e) 0)}

theme_set(theme_inbo(10))
theme_inbo <- theme_update(axis.title = element_text(colour = "black"), 
                           axis.text = element_text(colour = "black"),
                           legend.text = element_text(colour = "black", 
                                                      size = rel(0.8)),
                           plot.title = element_text(colour = "#843860"),
                           legend.key = element_rect(fill = "white"))
update_geom_defaults("point", aes(size = 2))
update_geom_defaults("line", aes(size = 0.25))

```

```{r Data}
WNMBE_Nieuw <- read_delim("data/Raw/WNMBE_Nieuw.csv", 
    ";", escape_double = FALSE, col_types = cols(Datum = col_date(format = "%d/%m/%Y")), 
    trim_ws = TRUE)

RST_Losse_Observaties <- read_delim("data/processed/RST_Losse_Observaties.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
```

```{r Data toevoegen}
minJaar <- max(RST_Losse_Observaties$Jaar) #Tot dit jaar zit de data er reeds in.
maxJaar <- year(Sys.Date()) #Hierdoor wordt het lopende jaar niet toegevoegd terwijl we de data behouden. 

#Filter tegen dubbels (zie parameters boven)
WNMBE_Nieuw2 <- WNMBE_Nieuw %>% 
  mutate(Jaar = year(Datum)) %>% 
  filter(Jaar > minJaar & Jaar < maxJaar) %>% 
  mutate(Maand = month(Datum)) %>% 
  mutate(Gebied = case_when(grepl("IJzervallei", Gebied) ~ "IJzervallei",
                            TRUE ~ Gebied))

#Waalse waarnemingen

Waalse_WNM <- data.frame()

Waalse_WNM <- Waalse_WNM %>% 
  mutate(Jaar = c(2019),
         Maximum_Wal = c(1),
         Gebieden_Wal = c(1)) %>% 
  add_row(Jaar = 2019,
         Maximum_Wal = 1,
         Gebieden_Wal = 1)

#Bereken het Maximum
Nieuwe_Data_max_gebied <- WNMBE_Nieuw2 %>% 
  group_by(Gebied, Jaar, Maand) %>% 
  summarise(MaxPerGebied = max(Aantal)) %>% 
  filter(Jaar < maxJaar, 
         Maand > 3, 
         Maand < 10) %>% 
  ungroup()


if(nrow(WNMBE_Nieuw2) > 0){
 write_delim(Nieuwe_Data_max_gebied, "./data/processed/RST_LosseWNM_MaxPerGebied.csv", delim = ";")
}

Nieuwe_Data <- 
  Nieuwe_Data_max_gebied %>% 
  group_by(Jaar) %>% 
  summarise(Maximum = sum(MaxPerGebied),
            Gebieden = n_distinct(Gebied))%>% 
  left_join(Waalse_WNM) %>% 
  mutate(Maximum_Bel = Maximum + Maximum_Wal,
         Gebieden_Bel = Gebieden + Gebieden_Wal) 

n_distinct(WNMBE_Nieuw2$Gebied)
max(WNMBE_Nieuw2$Aantal)
sum(WNMBE_Nieuw2$Aantal)/nrow(WNMBE_Nieuw2)

if(check(WNMBE_Nieuw2)==0){
  RST_Losse_Observaties2 <- RST_Losse_Observaties
  print("Geen Update")
}else{
  RST_Losse_Observaties2 <- rbind(RST_Losse_Observaties, Nieuwe_Data)
  write_delim(RST_Losse_Observaties2, "data/processed/RST_Losse_Observaties.csv", ";")
}
```

```{r grafiek vlaanderen}
talen <- c("NL","EN","DE")
extensies <- c(".eps", ".jpeg")
for(taal in talen){
  p <- ggplot(data = RST_Losse_Observaties2, aes(x = Jaar, y = Maximum))
  p <- p + geom_col() +
    geom_line(aes(x = Jaar, y = Gebieden))
  p <- p + scale_x_continuous(NULL, breaks = seq(2010, max(RST_Losse_Observaties2$Jaar), by = 1))
  p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
  if(taal == "NL"){
    p <- p + scale_y_continuous("Maandmaximum in Vlaanderen o.b.v. losse waarnemingen",breaks = seq(0, 20, by = 2), limits = c(0,20), expand = c(0,0))
  }else{
    if(taal == "EN"){
      p <- p + scale_y_continuous("Monthly maximum in Flanders based on individual observations",breaks = seq(0, 20, by = 2), limits = c(0,20),expand = c(0,0))
    }else{
      print("WARNING: Translate y-axis!! defaults to english")
      p <- p + scale_y_continuous("Monthly maximum in Flanders based on individual observations",breaks = seq(0, 20, by = 2), limits = c(0,20),expand = c(0,0))
    }
  }
  p <- p + theme(axis.title.y = element_text(size = 8))
  p <- p + theme(axis.line.x = element_line(color = "black", size = 0.5, linetype = "solid"))
  p <- p + theme(axis.line.y = element_line(color = "black", size = 0.5, linetype = "solid"))
  for(extensie in extensies){
    fn <- paste0("reports/figures/RST_Maandmaximum_Losse_Observaties_", taal , extensie)
    ggsave(fn, p)
  }

  print(p)
}

```

```{r grafiek belgie}
talen <- c("NL","EN","DE")
extensies <- c(".eps", ".jpeg")
for(taal in talen){
  p <- ggplot(data = RST_Losse_Observaties2, aes(x = Jaar, y = Maximum_Bel))
  p <- p + geom_col() +
    geom_line(aes(x = Jaar, y = Gebieden_Bel, colour = "black"), colour = "black", size = 1) 
  p <- p + scale_x_continuous(NULL, breaks = seq(2011, max(RST_Losse_Observaties2$Jaar), by = 1))
  p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
  if(taal == "NL"){
    p <- p + scale_y_continuous("Maandmaximum in België o.b.v. losse waarnemingen",breaks = seq(0, 40, by = 2), limits = c(0,40), expand = c(0,0))
  }else{
    if(taal == "EN"){
      p <- p + scale_y_continuous("Monthly maximum in Belgium based on individual observations",breaks = seq(0, 40, by = 2), limits = c(0,40),expand = c(0,0))
    }else{
      print("WARNING: Translate y-axis!! defaults to english")
      p <- p + scale_y_continuous("Monthly maximum in Belgium based on individual observations",breaks = seq(0, 400, by = 2), limits = c(0,40),expand = c(0,0))
    }
  }
  p <- p + theme(axis.title.y = element_text(size = 8))
  p <- p + theme(axis.line.x = element_line(color = "black", size = 0.5, linetype = "solid"))
  p <- p + theme(axis.line.y = element_line(color = "black", size = 0.5, linetype = "solid"))
  for(extensie in extensies){
    fn <- paste0("reports/figures/RST_Maandmaximum_Losse_Observaties_BEL_", taal , extensie)
    ggsave(fn, p)
  }

  print(p)
}

```