---
title: "Overwinterende_Rosse_Stekels"
author: "Sander Devisscher", "Tim Adriaens", "Koen Devos"
date: "23 juli 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  fig.width = 147 / 25.4,
  fig.height = 103 / 25.4,
  dpi = 300
)
```

# Voorbereiding

```{r libraries}
library(INBOtheme)
library(DBI)
library(odbc)
library(tidyverse)

theme_set(theme_inbo(10))
theme_inbo <- theme_update(axis.title = element_text(colour = "black"), 
                           axis.text = element_text(colour = "black"),
                           legend.text = element_text(colour = "black", 
                                                      size = rel(0.8)),
                           plot.title = element_text(colour = "#843860"),
                           legend.key = element_rect(fill = "white"))
update_geom_defaults("point", aes(size = 2))
update_geom_defaults("line", aes(size = 0.25))

check <- function(x){tryCatch(if(class(x) == 'logical') 1 else 1, error=function(e) 0)}
```

```{r Update data van WatervogelDatabank}
source(file = "./src/get_data/getdata_watervogeldatabank.R")
```

```{r Read data van WatervogelDatabank}
watervogeldb_data <- getdata_watervogeldatabank(158)
```

```{r data klaarzetten}
table(data$Month)
winter_helft1 <- c("October", "November", "December")
winter_helft2 <- c("January", "February", "March")

data <- watervogeldb_data %>% 
  filter(Samplestatus == "CHECKED") %>% 
  filter(Year >= 1979) %>% 
  filter(Month %in% winter_helft1 | Month %in% winter_helft2) %>% 
  dplyr::mutate("Winter" = case_when(Month %in% winter_helft1 ~ paste0(Year, "-", as.integer(Year) + 1),
                            Month %in% winter_helft2 ~ paste0(as.integer(Year) - 1 , "-", Year),
                            TRUE ~ NA_character_)) %>% 
  group_by(LocationWVKey, Winter, Month) %>% 
  summarise(maximum = max(TaxonCount, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(Winter, Month) %>% 
  summarise(sum = sum(maximum)) %>% 
  ungroup() %>% 
  group_by(Winter) %>% 
  summarise(Maximum = max(sum, na.rm = TRUE)) %>% 
  filter(Winter != "1978-1979")
```

```{r grafiekje}
talen <- c("NL","EN","DE")
extensies <- c(".eps", ".jpeg")
for(taal in talen){
  p <- ggplot(data = data, aes(x = Winter, y = Maximum))
  p <- p + geom_col()
  p <- p + scale_x_discrete(NULL)
  p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
  if(taal == "NL"){
    p <- p + scale_y_continuous("Aantal overwinterende rosse stekelstaarten",breaks = seq(0, 15, by = 2), limits = c(0,14), expand = c(0,0))
  }else{
    if(taal == "EN"){
      p <- p + scale_y_continuous("Number of wintering ruddy ducks",breaks = seq(0, 15, by = 2), limits = c(0,14),expand = c(0,0))
    }else{
      print("WARNING: Translate y-axis, defaults to english")
      p <- p + scale_y_continuous("Number of wintering ruddy ducks",breaks = seq(0, 15, by = 2), limits = c(0,14),expand = c(0,0))
    }
  }
  p <- p + theme(axis.line.x = element_line(color = "black", size = 0.5, linetype = "solid"))
  p <- p + theme(axis.line.y = element_line(color = "black", size = 0.5, linetype = "solid"))
  for(extensie in extensies){
    fn <- paste0("reports/figures/Overwinterende_rosse_stekelstaarten_", taal , extensie)
    ggsave(fn, p)
  }

  print(p)
}
```

```{r}
RST_Statistieken <- read_delim("data/processed/RST_Statistieken.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

n_gebieden <- watervogeldb_data %>% 
  filter(Samplestatus == "CHECKED") %>% 
  filter(Year >= 1979) %>% 
  filter(Month %in% winter_helft1 | Month %in% winter_helft2) %>% 
  dplyr::mutate("Winter" = case_when(Month %in% winter_helft1 ~ paste0(Year, "-", as.integer(Year) + 1),
                            Month %in% winter_helft2 ~ paste0(as.integer(Year) - 1 , "-", Year),
                            TRUE ~ NA_character_)) %>% 
  filter(TaxonCount > 0) %>% 
  group_by(Winter) %>% 
  summarise(gebieden_wintertelling = n_distinct(LocationWVKey))

RST_Statistieken <- RST_Statistieken %>% 
  mutate(max_wintertelling = tail(data$Maximum, 1),
         gebied_wintertelling = tail(n_gebieden$gebieden_wintertelling, 1))

write_delim(RST_Statistieken,"data/processed/RST_Statistieken.csv", ";")
```

