---
title: "RST_Beheersacties"
author: "Sander Devisscher, Tim Adriaens"
date: "25 juli 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(leaflet)
library(readxl)
library(sp)
library(leaflet)
library(leaflet.minicharts)
library(leaflet.extras)
library(leafem)
library(lubridate)
library(htmlwidgets)
library(tidyverse)
```

```{r stel crs'en in}
crs_wgs <- CRS("+proj=longlat +datum=WGS84 +no_defs ")
crs_bel <- CRS("+init=epsg:31370")
```

```{r get data}
source("./src/get_data/getdata_recorder_rst.r")

Data_Rosse_Stekelstaart <- getdata_recorder_rst()

Taxon_Rosse_Stekelstaart <- Data_Rosse_Stekelstaart$taxon
```

```{r}
table(Taxon_Rosse_Stekelstaart$SampleType, useNA = "ifany")
SampleTypes <- c("Afschot", "Afvangst")

table(Taxon_Rosse_Stekelstaart$EventLocation, useNA = "ifany")

zndr_EventLocation <- Taxon_Rosse_Stekelstaart %>% 
  filter(is.na(EventLocation)) #Allemaal met EventLocationName in de goede vorm dus als is.na(EventLocation) dan EventLocation == EventLocationName!!

Taxon_Rosse_Stekelstaart <- Taxon_Rosse_Stekelstaart %>% 
  mutate(EventLocation = case_when(is.na(EventLocation) ~ EventLocationName,
                                   TRUE ~ EventLocation))

Locaties <- Taxon_Rosse_Stekelstaart %>% 
  group_by(EventLocation) %>% 
  summarise(LambertX_Cent = mean(LambertX), LambertY_Cent = mean(LambertY), LambertX_Max = max(LambertX), LambertY_Max = max(LambertY), LambertX_Min = min(LambertX), LambertY_Min = min(LambertY)) %>% 
  mutate(Uncertainty_X = LambertX_Max - LambertX_Min, Uncertainty_Y = LambertY_Max - LambertY_Min) %>% select(EventLocation, LambertX_Cent, LambertY_Cent, Uncertainty_X, Uncertainty_Y)

Taxon_Rosse_Stekelstaart_totalen <- Taxon_Rosse_Stekelstaart %>% 
  filter(SampleType %in% SampleTypes) %>% 
  filter(Taxon_MeasurementUnit == "Count") %>% 
  mutate(EventDate2 = as.Date.character(EventDate, tryFormats = c("%d/%m/%Y"))) %>% 
  mutate(Year = year(EventDate2)) %>% 
  group_by(EventLocation, SampleType) %>% 
  summarise(Totaal = sum(as.numeric(Taxon_Data)))

Taxon_Rosse_Stekelstaart_int <- Taxon_Rosse_Stekelstaart %>% 
  filter(SampleType %in% SampleTypes) %>% 
  filter(Taxon_MeasurementUnit == "Count") %>% 
  mutate(EventDate2 = as.Date.character(EventDate, tryFormats = c("%d/%m/%Y"))) %>% 
  mutate(Year = year(EventDate2)) 

Taxon_Rosse_Stekelstaart2 <- Taxon_Rosse_Stekelstaart_int %>%  
  group_by(EventLocation, SampleType, Taxon_MeasurementQualifier) %>% 
  summarise(Aantal = sum(as.numeric(Taxon_Data))) %>% 
  spread(key = Taxon_MeasurementQualifier, value = Aantal, fill = 0) %>% 
  ungroup() %>% 
  left_join(y = Locaties) %>% 
  left_join(y = Taxon_Rosse_Stekelstaart_totalen) %>% 
  mutate(`Gevangen adult man` = `Gevangen AM`, 
         `Gevangen adult vrouw` = `Gevangen AV`) %>% 
  group_by(EventLocation) %>% 
  summarise(`Adult Man` = sum(`Adult Man`),
            `Adult Vrouw` = sum(`Adult Vrouw`),
            `Gevangen adult man` = sum(`Gevangen adult man`),
            `Gevangen adult vrouw` = sum(`Gevangen adult vrouw`),
            Juveniel = sum(Juveniel),
            Pulli = sum(Pulli),
            Totaal = sum(Totaal),
            LambertX_Cent = first(LambertX_Cent),
            LambertY_Cent = first(LambertY_Cent))

Taxon_Rosse_Stekelstaart2b <- Taxon_Rosse_Stekelstaart2 %>% 
  group_by(EventLocation) %>% 
  summarise(`Adult Man` = sum(`Adult Man`) + sum(`Gevangen adult man`),
            `Adult Vrouw` = sum(`Adult Vrouw`) + sum(`Gevangen adult vrouw`),
            Juveniel = sum(Juveniel) + sum(Pulli),
            Totaal = sum(Totaal),
            LambertX_Cent = first(LambertX_Cent),
            LambertY_Cent = first(LambertY_Cent))
```

```{r Kaartjes: prep}
totaal_geschoten <- sum(Taxon_Rosse_Stekelstaart2$Totaal)

colors <- c("#d7191c","#fdae61","#abd9e9","#2c7bb6", "#e66101","#4dac26")
colors2 <- c("#e66101","#4dac26")

vla_borders <- rgdal::readOGR("../backoffice-wild-analyse/Data/Spatial/flanders.geojson", "flanders", stringsAsFactors = FALSE)

nat2000 <- rgdal::readOGR("https://github.com/inbo/IAS_Species_Dashboard/raw/3_version1.0/Data/Spatial/natura2000_201301.geojson", "natura2000_201301", stringsAsFactors = FALSE)

proj4string(vla_borders) <- crs_bel
proj4string(nat2000) <- crs_bel

vla_borders <- spTransform(vla_borders, crs_wgs)
nat2000 <- spTransform(nat2000, crs_wgs)
```


```{r Kaartjes: afschot & afvangst apart, eval = FALSE}
coord <- Taxon_Rosse_Stekelstaart2 %>% 
  select(X = LambertX_Cent, Y = LambertY_Cent)

Taxon_Rosse_Stekelstaart_sp <- SpatialPointsDataFrame(coord,
                                                      data = Taxon_Rosse_Stekelstaart2,
                                                      proj4string = crs_bel)

Taxon_Rosse_Stekelstaart_sp <- spTransform(Taxon_Rosse_Stekelstaart_sp, crs_wgs)
Taxon_Rosse_Stekelstaart_sp$lng <- Taxon_Rosse_Stekelstaart_sp@coords[,1]
Taxon_Rosse_Stekelstaart_sp$lat <- Taxon_Rosse_Stekelstaart_sp@coords[,2]

map_split <- leaflet(Taxon_Rosse_Stekelstaart_sp) %>% 
  addPolygons(data = nat2000,
              color = "green",
              opacity = 1,
              weight = 1) %>% 
  addMinicharts(
    Taxon_Rosse_Stekelstaart_sp$lng, Taxon_Rosse_Stekelstaart_sp$lat,
    type = "pie",
    chartdata = Taxon_Rosse_Stekelstaart2[,c("Adult Man", "Adult Vrouw", "Juveniel", "Pulli","Gevangen adult man", "Gevangen adult vrouw")], 
    colorPalette = colors, 
    opacity = 0.75,
    width = 60 * sqrt(Taxon_Rosse_Stekelstaart2$Totaal) / sqrt(max(Taxon_Rosse_Stekelstaart2$Totaal)), transitionTime = 0,
    layerId = Taxon_Rosse_Stekelstaart2$EventLocation,
    legendPosition = "bottomright"
  ) %>% 
  addPolylines(data = spTransform(vla_borders, crs_wgs),
               color = "black",
               opacity = 1,
               weight = 2) %>% 
  addScaleBar(position = "bottomleft") %>% 
  addLogo(img = "https://cdn2.iconfinder.com/data/icons/map-and-navigation-12/48/57-512.png", src = "remote", position = "topright") %>% 
  setMapWidgetStyle(list(background= "white")) 


print(map_split)

mapview::mapshot(map_split, file = paste0(getwd(),"./reports/figures/easin_v_grid10k_split.jpeg"), remove_controls = c("zoomControl", "layersControl", "homeButton"), remove_url = TRUE)
```

```{r Kaartjes: alle acties samen, eval = FALSE}
coord <- Taxon_Rosse_Stekelstaart2b %>% 
  select(X = LambertX_Cent, Y = LambertY_Cent)

Taxon_Rosse_Stekelstaart_sp <- SpatialPointsDataFrame(coord,
                                                      data = Taxon_Rosse_Stekelstaart2b,
                                                      proj4string = crs_bel)

Taxon_Rosse_Stekelstaart_sp <- spTransform(Taxon_Rosse_Stekelstaart_sp, crs_wgs)
Taxon_Rosse_Stekelstaart_sp$lng <- Taxon_Rosse_Stekelstaart_sp@coords[,1]
Taxon_Rosse_Stekelstaart_sp$lat <- Taxon_Rosse_Stekelstaart_sp@coords[,2]

map_samen <- leaflet(Taxon_Rosse_Stekelstaart_sp) %>% 
  addPolygons(data = nat2000,
              color = "green",
              opacity = 1,
              weight = 1) %>% 
  addMinicharts(
    Taxon_Rosse_Stekelstaart_sp$lng, Taxon_Rosse_Stekelstaart_sp$lat,
    type = "pie",
    chartdata = Taxon_Rosse_Stekelstaart2b[,c("Adult Man", "Adult Vrouw", "Juveniel")], 
    colorPalette = colors, 
    opacity = 0.75,
    width = 60 * sqrt(Taxon_Rosse_Stekelstaart2b$Totaal) / sqrt(max(Taxon_Rosse_Stekelstaart2b$Totaal)), transitionTime = 0,
    layerId = Taxon_Rosse_Stekelstaart2b$EventLocation,
    legendPosition = "bottomright"
  ) %>% 
  addPolylines(data = spTransform(vla_borders, crs_wgs),
               color = "black",
               opacity = 1,
               weight = 2) %>% 
  addScaleBar(position = "bottomleft") %>% 
  addLogo(img = "https://cdn2.iconfinder.com/data/icons/map-and-navigation-12/48/57-512.png", src = "remote", position = "topright") %>% 
  setMapWidgetStyle(list(background= "white")) 


print(map_samen)

mapview::mapshot(map_samen, file = paste0(getwd(),"./reports/figures/easin_v_grid10k.jpeg"), remove_controls = c("zoomControl", "layersControl", "homeButton"), remove_url = TRUE)

#Export en move output
saveWidget(map, file="kaartje_beheersacties.html", selfcontained = TRUE)
file.copy("./kaartje_beheersacties.html", "./data/processed/kaartje_beheersacties.html")
file.remove("./kaartje_beheersacties.html")

```

```{r Tabel}
Jaren <- c("", 2009:max(Taxon_Rosse_Stekelstaart_int$Year))

Tabel <- data.frame(matrix(NA, nrow = 8, ncol = length(Jaren)))

colnames(Tabel) <- as.factor(Jaren)

temp <- data.frame(matrix(NA, nrow = length(Jaren), ncol = 1))
temp$Year <- Jaren 
temp$matrix.NA..nrow...length.Jaren...ncol...1. <- NULL

Taxon_Rosse_Stekelstaart_int$Year <- as.character(Taxon_Rosse_Stekelstaart_int$Year)

afschot_am <- Taxon_Rosse_Stekelstaart_int %>% 
  filter(Taxon_MeasurementQualifier == "Adult Man" & SampleType == "Afschot") %>% 
  group_by(Year) %>% 
  summarise(Aantal = sum(as.numeric(Taxon_Data))) %>% 
  right_join(y = temp, fill = "")
afschot_av <- Taxon_Rosse_Stekelstaart_int %>% 
  filter(Taxon_MeasurementQualifier == "Adult Vrouw" & SampleType == "Afschot") %>% 
  group_by(Year) %>% 
  summarise(Aantal = sum(as.numeric(Taxon_Data))) %>% 
  right_join(y = temp, fill = "")
afschot_juv <- Taxon_Rosse_Stekelstaart_int %>% 
  filter(Taxon_MeasurementQualifier == "Juveniel" | Taxon_MeasurementQualifier == "Pulli" & SampleType == "Afschot") %>% 
  group_by(Year) %>% 
  summarise(Aantal = sum(as.numeric(Taxon_Data))) %>% 
  right_join(y = temp)
vangst_am <- Taxon_Rosse_Stekelstaart_int %>% 
  filter(Taxon_MeasurementQualifier == "Gevangen AM"  & SampleType == "Afvangst") %>% 
  group_by(Year) %>% 
  summarise(Aantal = sum(as.numeric(Taxon_Data))) %>% 
  right_join(y = temp)
vangst_av <- Taxon_Rosse_Stekelstaart_int %>% 
  filter(Taxon_MeasurementQualifier == "Gevangen AV"  & SampleType == "Afvangst") %>% 
  group_by(Year) %>% 
  summarise(Aantal = sum(as.numeric(Taxon_Data))) %>% 
  right_join(y = temp)
totaal <- Taxon_Rosse_Stekelstaart_int %>% 
  group_by(Year) %>% 
  summarise(Aantal = sum(as.numeric(Taxon_Data))) %>% 
  right_join(y = temp)

Tabel[2,] <- afschot_am$Aantal
Tabel[3,] <- afschot_av$Aantal
Tabel[4,] <- afschot_juv$Aantal
Tabel[6,] <- vangst_am$Aantal
Tabel[7,] <- vangst_av$Aantal
Tabel[8,] <- totaal$Aantal

Tabel[1,1] <- "Afschot"
Tabel[2,1] <- "Adult Man"
Tabel[3,1] <- "Adult Vrouw"
Tabel[4,1] <- "Subadult/Pullus"
Tabel[5,1] <- "Vangst"
Tabel[6,1] <- "Adult man"
Tabel[7,1] <- "Adult vrouw"
Tabel[8,1] <- "Totaal"

Tabel$Totaal <- NA

afschot_am_totaal <- afschot_am %>% 
  summarise(Totaal = sum(Aantal, na.rm = TRUE))
afschot_av_totaal <- afschot_av %>% 
  summarise(Totaal = sum(Aantal, na.rm = TRUE))
afschot_juv_totaal <- afschot_juv %>% 
  summarise(Totaal = sum(Aantal, na.rm = TRUE))
vangst_am_totaal <- vangst_am %>% 
  summarise(Totaal = sum(Aantal, na.rm = TRUE))
vangst_av_totaal <- vangst_av %>% 
  summarise(Totaal = sum(Aantal, na.rm = TRUE))
totaal_totaal <- totaal %>% 
  summarise(Totaal = sum(Aantal, na.rm = TRUE))

Tabel$Totaal[2] <- afschot_am_totaal$Totaal
Tabel$Totaal[3] <- afschot_av_totaal$Totaal
Tabel$Totaal[4] <- afschot_juv_totaal$Totaal
Tabel$Totaal[6] <- vangst_am_totaal$Totaal
Tabel$Totaal[7] <- vangst_av_totaal$Totaal
Tabel$Totaal[8] <- totaal_totaal$Totaal

write_delim(Tabel, "./data/processed/Beheeracties_Tabel.csv", delim = ";", na = "")
```

