---
title: "Natuurindicatoren"
author: "Yasmine Verzelen"
date: "24 oktober 2017"
output: html_document
---

In dit script willen we de data van waarnemingen.be van GBIF halen, voor niet-inheemse planten en dieren.

Load packages
```{r}
library(rgbif)
library(curl)
library(ggplot2)
#library(INBOtheme)
```

Number of records in Waarnemingen.be datasets
```{r}
'Plants'
occ_count(datasetKey='7f5e4129-0717-428e-876a-464fbd5d9a47')
'Animals'
occ_count(datasetKey='9a0b66df-7535-4f28-9f4e-5bc11b8b096c')

```
Get the data from the datasets
```{r}
'Animals'
WnmBe_Animals <- occ_download_get(key = "0006839-171025204727650", overwrite = TRUE) %>% 
    occ_download_import(WnmBe_Animals_download, na.strings = c("", NA))
WnmBe_Animals$species <- as.character(WnmBe_Animals$species)

'Plants'
WnmBe_Plants <- occ_download_get(key = "0006843-171025204727650", overwrite = TRUE) %>% 
    occ_download_import(WnmBe_Plants_download, na.strings = c("", NA))

```

Merge the datasets
```{r}
WnmBe_All <- rbind(WnmBe_Animals, WnmBe_Plants)
```
Calculate the first occurence per species
```{r}
WnmBe_All <- subset(WnmBe_All, !is.na(species))
species <- unique(WnmBe_All$species)
species_list <- data.frame()
for(s in species){
  temp <- subset(WnmBe_All, species == s)
  temp2 <- data.frame(s)
  temp2$firstyear <- min(temp$year)
  temp2$Kingdom <- unique(temp$kingdom)
  temp2$
  species_list <- rbind(species_list, temp2)
}

remove(temp)
remove(temp2)

```

Calculate cumulative number of invasive species

```{r}

firstrecord <- min(species_list$firstyear)
newestrecord <- max(unique(WnmBe_All$year))
tijdspanne <- (newestrecord-firstrecord)+1

new_species <- data.frame()
temp2 <- data.frame(1)
t <- firstrecord

for(i in 1:tijdspanne){
  temp <- subset(species_list, firstyear == t)
  temp2$n <- nrow(temp)
  temp2$t <- t
  new_species <- rbind(new_species, temp2)
  t <- t + 1
}

new_species$X1 <- NULL
new_species$cumul <- cumsum(new_species$n)

plot <- ggplot(new_species, aes(x = t, y=cumul))
plot <- plot + geom_line()
print(plot)

```

